# Generated by Django 5.1.5 on 2025-02-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_member_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='preacher',
            field=models.CharField(max_length=100),
        ),
    ]
