# Generated by Django 5.1.5 on 2025-02-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_eventregistration_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventregistration',
            table='event_registrations',
        ),
    ]
