# Generated by Django 5.1.5 on 2025-02-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_member_options_member_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
    ]
