# Generated by Django 5.1.5 on 2025-02-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_member_profile_picture_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(choices=[('Mobile Money', 'Mobile Money'), ('Cash', 'Cash')], default='Mobile Money', max_length=100),
        ),
    ]
