# Generated by Django 5.1.5 on 2025-02-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_member_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='role',
        ),
    ]
