# Generated by Django 5.1.5 on 2025-02-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_contactmessage_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveservice',
            name='preacher',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='liveservice',
            name='service_name',
            field=models.CharField(max_length=50),
        ),
    ]
