# Generated by Django 5.1.5 on 2025-02-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_liveservice_preacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
