# Generated by Django 5.1.5 on 2025-03-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_deposit_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='phone',
        ),
    ]
