# Generated by Django 5.1.5 on 2025-04-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_adminactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='notices/default.jpg', null=True, upload_to='notice_images/')),
            ],
        ),
    ]
